spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password:
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always
  port: 8081
#
#jwt:
#  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
